event/urls.py
from django.urls import path

from event import views

app_name = "event"
urlpatterns = [
    path('', views.index, name='index'),
    path('table/', views.table, name="table"),
]

sample/urls.py
from django.contrib import admin
from django.urls import path, include
from sample import views

urlpatterns = [
    path("", views.index, name="index"),
    path("get/", views.index_get, name="index_get"),
    path("post/", views.index_post, name="index_post"),
    path("event/", include("event.urls")),
    path("admin/", admin.site.urls),
]

event/models.py
from django.db import models

# Create your models here.

event/views.py
from django.shortcuts import render


def index(request):
    return render(request, "event/index.html", {})


def table(request):
    return render(request, "event/table.html", {})

sample/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseBadRequest
from django.views.decorators.csrf import csrf_exempt


def index(request):
    return render(request, "sample/index.html", {})


def index_get(request):
    if request.method != "GET":
        return HttpResponseBadRequest()

    try:
        user_name = request.GET.get("user", "default")
        return HttpResponse("access done! by user=" + user_name)
    except Exception as e:
        print("error occured.")
        print(e)
        return HttpResponseBadRequest()


@csrf_exempt
def index_post(request):
    if request.method != "POST":
        return HttpResponseBadRequest()

    try:
        body_unicode = request.body.decode("utf-8")
        name = request.POST.get("name", "規定の名前")
        email = request.POST.get("email", "規定のEmail")

        dic = {"body_unicode": body_unicode, "name": name, "email": email}

        return render(request, "sample/post.html", dic)
    except Exception as e:
        print("error occured.")
        print(e)
        return HttpResponseBadRequest()

templates/event/index.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <title>イベントトップページ</title>
</head>

<body>
    イベントトップメニュー
    <ul>
        <li><a href="{% url 'event:table' %}">イベント一覧</a></li>
        <li>リンクB</li>
        <li>リンクC</li>
    </ul>
</body>

</html>

templates/event/table.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <title>イベント一覧ページ</title>
</head>

<body>
    イベント一覧
    <ul>
        <li>イベントA</li>
        <li>イベントB</li>
        <li>イベントC</li>
        <li>イベントD</li>
        <li>イベントE</li>
    </ul>
</body>

</html>

templates/sample/index.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <title>トップページ</title>
</head>

<body>
    メニュー
    <ul>
        <li>リンクA</li>
        <li>リンクB</li>
        <li>リンクC</li>
    </ul>

    <form method="POST" action="post/">
        名前: <input type="text" name="name">
        Email: <input type="text" name="email">
        <input type="submit">
    </form>
</body>

</html>

templates/sample/post.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <title>POST情報表示ページ</title>
</head>

<body>
    <ul>
        <li>{{body_unicode}}</li>
        <li>{{name}}</li>
        <li>{{email}}</li>
    </ul>
</body>

</html>